services:
  - type: web
    name: sap-api-receiver
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SAP_USER
        sync: false
      - key: SAP_PASSWORD
        sync: false
      - key: SAP_ASHOST
        sync: false
      - key: SAP_SYSNR
        value: "00"
      - key: SAP_CLIENT
        value: "100"
      - key: SAP_LANG
        value: "EN"
